services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./src:/usr/src
    ports:
      - "8080:80"

  wordpress:
    container_name: wordpress
    volumes:
      - ./src:/usr/src
    build:
      context: ./src
      dockerfile: dockerfile
    depends_on:
      - database

  database:
    container_name: wordpress-database
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=wordpressDB
