services:
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./src:/usr/src
    ports:
      - "8080:80"
    tty: true
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    environment:
      - DB_HOST=database
      - DB_USER=user
      - PASSWORD=examplepass
      - DB_NAME=wordpress-database
    volumes:
      - ./src:/usr/src
    build:
      context: ./src
      dockerfile: dockerfile
    depends_on:
      - database

  database:
    container_name: wordpress-database
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=wordpressDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=examplepass
    volumes:
      - database:/var/lib/mysql
    ports:
      - 8001:5432

volumes:
  database:
