FROM php:8.1-fpm
COPY . /usr/src/
WORKDIR /usr/src/

RUN apt-get update && apt-get install -y libpng-dev libjpeg-dev
RUN rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-configure gd --with-jpeg
RUN docker-php-ext-install gd

RUN docker-php-ext-install mysqli

RUN chown -R www-data:www-data /usr/src